x=dict()
print(x)
print(type(x))
print(len(x))
y={}
print(y)
z={"python":7,"java":99,"hadoop":89}
print(z)
print(len(z))
p={10:"lokesh",123.123:True,False:3+4j}
print(p)
print(id(p))
print(len(p))
print(z["python"])
print(z["java"])
p[10]="sarada"
print(p)
print(id(p))
#dictionary methods
x={"python":89,"java":90,"hadoop":78}
print(x)
y=x.copy()
print(y)
print(x.get("hadoop"))
print(x.get("java"))
x.pop("java")
print(x)
x.popitem()
print(x)
help(dict())
print(x)
print(x.popitem())
